// ---------------------------------------------------------------------------
// Node name enum — all known constructor/variant names in patterns
// ---------------------------------------------------------------------------

/// All known node/constructor names used in patterns.
/// Validated at parse time so typos are caught early.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum NodeName {
    // Statement kinds
    Assignment,
    If,
    While,
    DoWhile,
    For,
    Return,
    Block,
    Label,
    Comment,
    Assembly,
    Declaration,
    Call,
    Goto,
    Empty,
    Break,
    Continue,
    Undefined,
    // Expression kinds (Call, Undefined shared with stmt — same variant)
    Variable,
    Literal,
    UnaryOp,
    BinaryOp,
    Ternary,
    Cast,
    Deref,
    AddressOf,
    ArrayAccess,
    MemberAccess,
    Unknown,
    ArchitectureBitSize,
    ArchitectureByteSize,
    // Binary operators
    Add,
    Sub,
    Mul,
    Div,
    Mod,
    BitAnd,
    BitOr,
    BitXor,
    LogicAnd,
    LogicOr,
    Equal,
    NotEqual,
    Less,
    LessEqual,
    Greater,
    GreaterEqual,
    LeftShift,
    RightShift,
    // Unary operators
    Negate,
    Not,
    BitNot,
    PreInc,
    PreDec,
    PostInc,
    PostDec,
    CastSigned,
    CastUnsigned,
    // Value types
    Void,
    Int,
    Int8,
    Int16,
    Int32,
    Int64,
    UInt,
    UInt8,
    UInt16,
    UInt32,
    UInt64,
    Char,
    Float,
    Double,
    Bool,
    // Bool literal values
    True,
    False,
}

impl NodeName {
    pub fn as_str(self) -> &'static str {
        match self {
            NodeName::Assignment => "Assignment",
            NodeName::If => "If",
            NodeName::While => "While",
            NodeName::DoWhile => "DoWhile",
            NodeName::For => "For",
            NodeName::Return => "Return",
            NodeName::Block => "Block",
            NodeName::Label => "Label",
            NodeName::Comment => "Comment",
            NodeName::Assembly => "Assembly",
            NodeName::Declaration => "Declaration",
            NodeName::Call => "Call",
            NodeName::Goto => "Goto",
            NodeName::Empty => "Empty",
            NodeName::Break => "Break",
            NodeName::Continue => "Continue",
            NodeName::Undefined => "Undefined",
            NodeName::Variable => "Variable",
            NodeName::Literal => "Literal",
            NodeName::UnaryOp => "UnaryOp",
            NodeName::BinaryOp => "BinaryOp",
            NodeName::Ternary => "Ternary",
            NodeName::Cast => "Cast",
            NodeName::Deref => "Deref",
            NodeName::AddressOf => "AddressOf",
            NodeName::ArrayAccess => "ArrayAccess",
            NodeName::MemberAccess => "MemberAccess",
            NodeName::Unknown => "Unknown",
            NodeName::ArchitectureBitSize => "ArchitectureBitSize",
            NodeName::ArchitectureByteSize => "ArchitectureByteSize",
            NodeName::Add => "Add",
            NodeName::Sub => "Sub",
            NodeName::Mul => "Mul",
            NodeName::Div => "Div",
            NodeName::Mod => "Mod",
            NodeName::BitAnd => "BitAnd",
            NodeName::BitOr => "BitOr",
            NodeName::BitXor => "BitXor",
            NodeName::LogicAnd => "LogicAnd",
            NodeName::LogicOr => "LogicOr",
            NodeName::Equal => "Equal",
            NodeName::NotEqual => "NotEqual",
            NodeName::Less => "Less",
            NodeName::LessEqual => "LessEqual",
            NodeName::Greater => "Greater",
            NodeName::GreaterEqual => "GreaterEqual",
            NodeName::LeftShift => "LeftShift",
            NodeName::RightShift => "RightShift",
            NodeName::Negate => "Negate",
            NodeName::Not => "Not",
            NodeName::BitNot => "BitNot",
            NodeName::PreInc => "PreInc",
            NodeName::PreDec => "PreDec",
            NodeName::PostInc => "PostInc",
            NodeName::PostDec => "PostDec",
            NodeName::CastSigned => "CastSigned",
            NodeName::CastUnsigned => "CastUnsigned",
            NodeName::Void => "Void",
            NodeName::Int => "Int",
            NodeName::Int8 => "Int8",
            NodeName::Int16 => "Int16",
            NodeName::Int32 => "Int32",
            NodeName::Int64 => "Int64",
            NodeName::UInt => "UInt",
            NodeName::UInt8 => "UInt8",
            NodeName::UInt16 => "UInt16",
            NodeName::UInt32 => "UInt32",
            NodeName::UInt64 => "UInt64",
            NodeName::Char => "Char",
            NodeName::Float => "Float",
            NodeName::Double => "Double",
            NodeName::Bool => "Bool",
            NodeName::True => "true",
            NodeName::False => "false",
        }
    }

    pub fn from_ident(s: &str) -> Option<NodeName> {
        match s {
            "Assignment" => Some(NodeName::Assignment),
            "If" => Some(NodeName::If),
            "While" => Some(NodeName::While),
            "DoWhile" => Some(NodeName::DoWhile),
            "For" => Some(NodeName::For),
            "Return" => Some(NodeName::Return),
            "Block" => Some(NodeName::Block),
            "Label" => Some(NodeName::Label),
            "Comment" => Some(NodeName::Comment),
            "Assembly" => Some(NodeName::Assembly),
            "Declaration" => Some(NodeName::Declaration),
            "Call" => Some(NodeName::Call),
            "Goto" => Some(NodeName::Goto),
            "Empty" => Some(NodeName::Empty),
            "Break" => Some(NodeName::Break),
            "Continue" => Some(NodeName::Continue),
            "Undefined" => Some(NodeName::Undefined),
            "Variable" => Some(NodeName::Variable),
            "Literal" => Some(NodeName::Literal),
            "UnaryOp" => Some(NodeName::UnaryOp),
            "BinaryOp" => Some(NodeName::BinaryOp),
            "Ternary" => Some(NodeName::Ternary),
            "Cast" => Some(NodeName::Cast),
            "Deref" => Some(NodeName::Deref),
            "AddressOf" => Some(NodeName::AddressOf),
            "ArrayAccess" => Some(NodeName::ArrayAccess),
            "MemberAccess" => Some(NodeName::MemberAccess),
            "Unknown" => Some(NodeName::Unknown),
            "ArchitectureBitSize" => Some(NodeName::ArchitectureBitSize),
            "ArchitectureByteSize" => Some(NodeName::ArchitectureByteSize),
            "Add" => Some(NodeName::Add),
            "Sub" => Some(NodeName::Sub),
            "Mul" => Some(NodeName::Mul),
            "Div" => Some(NodeName::Div),
            "Mod" => Some(NodeName::Mod),
            "BitAnd" => Some(NodeName::BitAnd),
            "BitOr" => Some(NodeName::BitOr),
            "BitXor" => Some(NodeName::BitXor),
            "LogicAnd" => Some(NodeName::LogicAnd),
            "LogicOr" => Some(NodeName::LogicOr),
            "Equal" => Some(NodeName::Equal),
            "NotEqual" => Some(NodeName::NotEqual),
            "Less" => Some(NodeName::Less),
            "LessEqual" => Some(NodeName::LessEqual),
            "Greater" => Some(NodeName::Greater),
            "GreaterEqual" => Some(NodeName::GreaterEqual),
            "LeftShift" => Some(NodeName::LeftShift),
            "RightShift" => Some(NodeName::RightShift),
            "Negate" => Some(NodeName::Negate),
            "Not" => Some(NodeName::Not),
            "BitNot" => Some(NodeName::BitNot),
            "PreInc" => Some(NodeName::PreInc),
            "PreDec" => Some(NodeName::PreDec),
            "PostInc" => Some(NodeName::PostInc),
            "PostDec" => Some(NodeName::PostDec),
            "CastSigned" => Some(NodeName::CastSigned),
            "CastUnsigned" => Some(NodeName::CastUnsigned),
            "Void" => Some(NodeName::Void),
            "Int" => Some(NodeName::Int),
            "Int8" => Some(NodeName::Int8),
            "Int16" => Some(NodeName::Int16),
            "Int32" => Some(NodeName::Int32),
            "Int64" => Some(NodeName::Int64),
            "UInt" => Some(NodeName::UInt),
            "UInt8" => Some(NodeName::UInt8),
            "UInt16" => Some(NodeName::UInt16),
            "UInt32" => Some(NodeName::UInt32),
            "UInt64" => Some(NodeName::UInt64),
            "Char" => Some(NodeName::Char),
            "Float" => Some(NodeName::Float),
            "Double" => Some(NodeName::Double),
            "Bool" => Some(NodeName::Bool),
            "true" => Some(NodeName::True),
            "false" => Some(NodeName::False),
            _ => None,
        }
    }
}

// ---------------------------------------------------------------------------
// Fits type enum
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct CaptureRef(String);

impl CaptureRef {
    pub fn new(name: impl Into<String>) -> Self {
        Self(name.into())
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FitsTypeName {
    Int8,
    Int16,
    Int32,
    Int64,
    Int,
}

#[derive(Debug, Clone)]
pub enum FitsTarget {
    TypeName(FitsTypeName),
    Capture(CaptureRef),
}
