use crate::{abstract_syntax_tree::objects::*, ir::statements::IrStatement};

#[derive(Debug, Clone)]
pub enum AstStatement {
    Declaration(AstVariable, Option<Wrapped<AstExpression>>),
    Assignment(Wrapped<AstExpression>, Wrapped<AstExpression>),
    If(
        Wrapped<AstExpression>,
        Vec<Wrapped<AstStatement>>,
        Option<Vec<Wrapped<AstStatement>>>,
    ),
    While(Wrapped<AstExpression>, Vec<Wrapped<AstStatement>>),
    For(
        Box<Wrapped<AstStatement>>,
        Wrapped<AstExpression>,
        Box<Wrapped<AstStatement>>,
        Vec<Wrapped<AstStatement>>,
    ),
    Return(Option<Wrapped<AstExpression>>),
    Call(AstCall),
    Label(String /* TODO need to change */),
    Goto(AstJumpTarget),
    Block(Vec<Wrapped<AstStatement>>),
    Assembly(String),
    Undefined,
    Exception(&'static str),
    Comment(String),
    Ir(
        Box<(
            Option<u32>, /* ir index. only used at ir analyzation. none if generated by analysis */
            IrStatement,
        )>,
    ),
    Empty,
    /// switch(expr) { case val: body; ... default: body; }
    Switch(
        Wrapped<AstExpression>,
        Vec<(AstLiteral, Vec<Wrapped<AstStatement>>)>,
        Option<Vec<Wrapped<AstStatement>>>,
    ),
    /// break statement (exits innermost loop/switch)
    Break,
    /// continue statement (jumps to loop header)
    Continue,
    /// do { body } while (condition)
    DoWhile(Wrapped<AstExpression>, Vec<Wrapped<AstStatement>>),
}
