// This file was automatically generated by ts_bind, do not modify it manually

export interface IrInspectResult {
   instruction: string;
   statements: (string)[] | null;
   data_accesses: (string)[] | null;
   data_access_per_ir: (string)[] | null;
}
