// Generated by cargo ts

export interface IrInspectResult {
   instruction: string;
   statements: (IrInspectResultSingle)[];
}

export interface IrInspectResultSingle {
   statement: string;
   dataAccesses: (string)[];
   dataAccessPerIr: (string)[];
}

export interface KnownSection {
   startAddress: number;
   endAddress: number | null;
   analyzed: boolean;
}
