#![allow(dead_code)]
//! Module that contains structure that contains section's information
//!
//!
//! 섹션에 대한 정보를 담은 구조체가 들어있는 모듈

/// Section Information Struct.
/// This struct contains section's data.
///
///
/// 섹션에 대한 정보가 들어있는 구조체
#[derive(Debug, Eq, Hash, PartialEq, Clone)]
pub struct Section {
    /// Section Id
    /// This Id generated by Fireball Library, not original file.
    ///
    /// 섹션 식별코드
    /// 원본 파일에서 존재하지 않는 정보이며, 라이브러리에서 가상으로 생성한 정보이다.
    pub(crate) id: usize,
    /// .text와 같은 이름
    pub(crate) name: String,
    /// 섹션의 이름
    pub(crate) real_name: Option<String>,
    /// Virtual Address of Section's Start
    ///
    /// 섹션의 시작지점의 가상주소
    ///
    /// Ex.) 0x1000
    pub(crate) virtual_address: u64,
    /// Size of Section's Virtual Address
    ///
    /// 섹션의 가상 주소의 크기
    ///
    /// Ex.) 0x1E00 means, when section start from 0x1000, this section's end is 0x2E00
    pub(crate) virtual_size: u64,
    /// File Offset of Section's Start
    ///
    /// 섹션의 시작부분에 매칭되는 파일 오프셋
    pub(crate) file_offset: u64,
    /// Size of Section in File
    ///
    /// 파일 내부에 존재하는 섹션의 크기
    pub(crate) size_of_file: u64,
}

// 섹션 정보는 수정되지 않으므로 Send를 구현해도 된다.
unsafe impl Send for Section {}

// format!이나 println!등에서 사용할 때 섹션의 가상주소가 표시되도록 구현
impl std::fmt::Display for Section {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{:#X} - {:#X}",
            self.virtual_address,
            self.virtual_address + self.virtual_size
        )
    }
}

/// 테스트 모듈
#[cfg(test)]
mod tests {
    use super::Section;

    /// Section구조체를 Display로 출력했을 때 제대로 출력되는지 확인하기 위한 테스트
    #[test]
    fn display_test() {
        let section = Section {
            id: 10,
            name: String::from("test"),
            real_name: Some("TestSection".to_owned()),
            virtual_address: 0x1000,
            virtual_size: 0x2A00,
            file_offset: 0x30B0,
            size_of_file: 0x400C,
        };

        assert_eq!(format!("{}", section), "0x1000 - 0x3A00");
    }
}
