//! API prototype database for common Windows/POSIX functions.
//!
//! Seeds parameter and return type information for known library functions
//! to improve decompilation output quality.

/// Prototype of a known API function.
#[derive(Debug, Clone, Copy)]
pub struct ApiPrototype {
    pub name: &'static str,
    pub return_type: &'static str,
    pub param_count: usize,
    pub param_types: &'static [&'static str],
    pub is_noreturn: bool,
    pub is_pure: bool,
}

/// Look up a known API by name (case-insensitive).
pub fn lookup_api(name: &str) -> Option<&'static ApiPrototype> {
    let name_lower = name.to_ascii_lowercase();
    KNOWN_APIS
        .iter()
        .find(|api| api.name.to_ascii_lowercase() == name_lower)
}

/// Look up by exact name (faster, case-sensitive).
pub fn lookup_api_exact(name: &str) -> Option<&'static ApiPrototype> {
    KNOWN_APIS.iter().find(|api| api.name == name)
}

/// Static table of known API prototypes.
pub static KNOWN_APIS: &[ApiPrototype] = &[
    // === C standard library ===
    ApiPrototype {
        name: "malloc",
        return_type: "void*",
        param_count: 1,
        param_types: &["size_t"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "calloc",
        return_type: "void*",
        param_count: 2,
        param_types: &["size_t", "size_t"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "realloc",
        return_type: "void*",
        param_count: 2,
        param_types: &["void*", "size_t"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "free",
        return_type: "void",
        param_count: 1,
        param_types: &["void*"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "memcpy",
        return_type: "void*",
        param_count: 3,
        param_types: &["void*", "const void*", "size_t"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "memmove",
        return_type: "void*",
        param_count: 3,
        param_types: &["void*", "const void*", "size_t"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "memset",
        return_type: "void*",
        param_count: 3,
        param_types: &["void*", "int", "size_t"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "memcmp",
        return_type: "int",
        param_count: 3,
        param_types: &["const void*", "const void*", "size_t"],
        is_noreturn: false,
        is_pure: true,
    },
    ApiPrototype {
        name: "strlen",
        return_type: "size_t",
        param_count: 1,
        param_types: &["const char*"],
        is_noreturn: false,
        is_pure: true,
    },
    ApiPrototype {
        name: "strcmp",
        return_type: "int",
        param_count: 2,
        param_types: &["const char*", "const char*"],
        is_noreturn: false,
        is_pure: true,
    },
    ApiPrototype {
        name: "strncmp",
        return_type: "int",
        param_count: 3,
        param_types: &["const char*", "const char*", "size_t"],
        is_noreturn: false,
        is_pure: true,
    },
    ApiPrototype {
        name: "strcpy",
        return_type: "char*",
        param_count: 2,
        param_types: &["char*", "const char*"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "strncpy",
        return_type: "char*",
        param_count: 3,
        param_types: &["char*", "const char*", "size_t"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "strcat",
        return_type: "char*",
        param_count: 2,
        param_types: &["char*", "const char*"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "strchr",
        return_type: "char*",
        param_count: 2,
        param_types: &["const char*", "int"],
        is_noreturn: false,
        is_pure: true,
    },
    ApiPrototype {
        name: "strstr",
        return_type: "char*",
        param_count: 2,
        param_types: &["const char*", "const char*"],
        is_noreturn: false,
        is_pure: true,
    },
    ApiPrototype {
        name: "printf",
        return_type: "int",
        param_count: 1,
        param_types: &["const char*"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "sprintf",
        return_type: "int",
        param_count: 2,
        param_types: &["char*", "const char*"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "snprintf",
        return_type: "int",
        param_count: 3,
        param_types: &["char*", "size_t", "const char*"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "fprintf",
        return_type: "int",
        param_count: 2,
        param_types: &["FILE*", "const char*"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "puts",
        return_type: "int",
        param_count: 1,
        param_types: &["const char*"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "fopen",
        return_type: "FILE*",
        param_count: 2,
        param_types: &["const char*", "const char*"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "fclose",
        return_type: "int",
        param_count: 1,
        param_types: &["FILE*"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "fread",
        return_type: "size_t",
        param_count: 4,
        param_types: &["void*", "size_t", "size_t", "FILE*"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "fwrite",
        return_type: "size_t",
        param_count: 4,
        param_types: &["const void*", "size_t", "size_t", "FILE*"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "atoi",
        return_type: "int",
        param_count: 1,
        param_types: &["const char*"],
        is_noreturn: false,
        is_pure: true,
    },
    ApiPrototype {
        name: "atol",
        return_type: "long",
        param_count: 1,
        param_types: &["const char*"],
        is_noreturn: false,
        is_pure: true,
    },
    ApiPrototype {
        name: "exit",
        return_type: "void",
        param_count: 1,
        param_types: &["int"],
        is_noreturn: true,
        is_pure: false,
    },
    ApiPrototype {
        name: "abort",
        return_type: "void",
        param_count: 0,
        param_types: &[],
        is_noreturn: true,
        is_pure: false,
    },
    ApiPrototype {
        name: "qsort",
        return_type: "void",
        param_count: 4,
        param_types: &[
            "void*",
            "size_t",
            "size_t",
            "int(*)(const void*, const void*)",
        ],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "bsearch",
        return_type: "void*",
        param_count: 5,
        param_types: &[
            "const void*",
            "const void*",
            "size_t",
            "size_t",
            "int(*)(const void*, const void*)",
        ],
        is_noreturn: false,
        is_pure: true,
    },
    // === Windows API ===
    ApiPrototype {
        name: "CreateFileA",
        return_type: "HANDLE",
        param_count: 7,
        param_types: &[
            "LPCSTR",
            "DWORD",
            "DWORD",
            "LPSECURITY_ATTRIBUTES",
            "DWORD",
            "DWORD",
            "HANDLE",
        ],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "CreateFileW",
        return_type: "HANDLE",
        param_count: 7,
        param_types: &[
            "LPCWSTR",
            "DWORD",
            "DWORD",
            "LPSECURITY_ATTRIBUTES",
            "DWORD",
            "DWORD",
            "HANDLE",
        ],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "CloseHandle",
        return_type: "BOOL",
        param_count: 1,
        param_types: &["HANDLE"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "ReadFile",
        return_type: "BOOL",
        param_count: 5,
        param_types: &["HANDLE", "LPVOID", "DWORD", "LPDWORD", "LPOVERLAPPED"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "WriteFile",
        return_type: "BOOL",
        param_count: 5,
        param_types: &["HANDLE", "LPCVOID", "DWORD", "LPDWORD", "LPOVERLAPPED"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "VirtualAlloc",
        return_type: "LPVOID",
        param_count: 4,
        param_types: &["LPVOID", "SIZE_T", "DWORD", "DWORD"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "VirtualFree",
        return_type: "BOOL",
        param_count: 3,
        param_types: &["LPVOID", "SIZE_T", "DWORD"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "VirtualProtect",
        return_type: "BOOL",
        param_count: 4,
        param_types: &["LPVOID", "SIZE_T", "DWORD", "PDWORD"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "GetProcAddress",
        return_type: "FARPROC",
        param_count: 2,
        param_types: &["HMODULE", "LPCSTR"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "LoadLibraryA",
        return_type: "HMODULE",
        param_count: 1,
        param_types: &["LPCSTR"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "LoadLibraryW",
        return_type: "HMODULE",
        param_count: 1,
        param_types: &["LPCWSTR"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "GetModuleHandleA",
        return_type: "HMODULE",
        param_count: 1,
        param_types: &["LPCSTR"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "GetModuleHandleW",
        return_type: "HMODULE",
        param_count: 1,
        param_types: &["LPCWSTR"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "GetLastError",
        return_type: "DWORD",
        param_count: 0,
        param_types: &[],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "SetLastError",
        return_type: "void",
        param_count: 1,
        param_types: &["DWORD"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "HeapAlloc",
        return_type: "LPVOID",
        param_count: 3,
        param_types: &["HANDLE", "DWORD", "SIZE_T"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "HeapFree",
        return_type: "BOOL",
        param_count: 3,
        param_types: &["HANDLE", "DWORD", "LPVOID"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "GetProcessHeap",
        return_type: "HANDLE",
        param_count: 0,
        param_types: &[],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "ExitProcess",
        return_type: "void",
        param_count: 1,
        param_types: &["UINT"],
        is_noreturn: true,
        is_pure: false,
    },
    ApiPrototype {
        name: "TerminateProcess",
        return_type: "BOOL",
        param_count: 2,
        param_types: &["HANDLE", "UINT"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "CreateThread",
        return_type: "HANDLE",
        param_count: 6,
        param_types: &[
            "LPSECURITY_ATTRIBUTES",
            "SIZE_T",
            "LPTHREAD_START_ROUTINE",
            "LPVOID",
            "DWORD",
            "LPDWORD",
        ],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "WaitForSingleObject",
        return_type: "DWORD",
        param_count: 2,
        param_types: &["HANDLE", "DWORD"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "RegOpenKeyExA",
        return_type: "LONG",
        param_count: 5,
        param_types: &["HKEY", "LPCSTR", "DWORD", "REGSAM", "PHKEY"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "RegOpenKeyExW",
        return_type: "LONG",
        param_count: 5,
        param_types: &["HKEY", "LPCWSTR", "DWORD", "REGSAM", "PHKEY"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "RegQueryValueExA",
        return_type: "LONG",
        param_count: 6,
        param_types: &["HKEY", "LPCSTR", "LPDWORD", "LPDWORD", "LPBYTE", "LPDWORD"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "RegCloseKey",
        return_type: "LONG",
        param_count: 1,
        param_types: &["HKEY"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "MessageBoxA",
        return_type: "int",
        param_count: 4,
        param_types: &["HWND", "LPCSTR", "LPCSTR", "UINT"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "MessageBoxW",
        return_type: "int",
        param_count: 4,
        param_types: &["HWND", "LPCWSTR", "LPCWSTR", "UINT"],
        is_noreturn: false,
        is_pure: false,
    },
    // === POSIX ===
    ApiPrototype {
        name: "open",
        return_type: "int",
        param_count: 2,
        param_types: &["const char*", "int"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "close",
        return_type: "int",
        param_count: 1,
        param_types: &["int"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "read",
        return_type: "ssize_t",
        param_count: 3,
        param_types: &["int", "void*", "size_t"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "write",
        return_type: "ssize_t",
        param_count: 3,
        param_types: &["int", "const void*", "size_t"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "mmap",
        return_type: "void*",
        param_count: 6,
        param_types: &["void*", "size_t", "int", "int", "int", "off_t"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "munmap",
        return_type: "int",
        param_count: 2,
        param_types: &["void*", "size_t"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "mprotect",
        return_type: "int",
        param_count: 3,
        param_types: &["void*", "size_t", "int"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "fork",
        return_type: "pid_t",
        param_count: 0,
        param_types: &[],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "execve",
        return_type: "int",
        param_count: 3,
        param_types: &["const char*", "char*const[]", "char*const[]"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "socket",
        return_type: "int",
        param_count: 3,
        param_types: &["int", "int", "int"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "connect",
        return_type: "int",
        param_count: 3,
        param_types: &["int", "const struct sockaddr*", "socklen_t"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "send",
        return_type: "ssize_t",
        param_count: 4,
        param_types: &["int", "const void*", "size_t", "int"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "recv",
        return_type: "ssize_t",
        param_count: 4,
        param_types: &["int", "void*", "size_t", "int"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "pthread_create",
        return_type: "int",
        param_count: 4,
        param_types: &[
            "pthread_t*",
            "const pthread_attr_t*",
            "void*(*)(void*)",
            "void*",
        ],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "pthread_join",
        return_type: "int",
        param_count: 2,
        param_types: &["pthread_t", "void**"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "pthread_mutex_lock",
        return_type: "int",
        param_count: 1,
        param_types: &["pthread_mutex_t*"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "pthread_mutex_unlock",
        return_type: "int",
        param_count: 1,
        param_types: &["pthread_mutex_t*"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "dlopen",
        return_type: "void*",
        param_count: 2,
        param_types: &["const char*", "int"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "dlsym",
        return_type: "void*",
        param_count: 2,
        param_types: &["void*", "const char*"],
        is_noreturn: false,
        is_pure: false,
    },
    ApiPrototype {
        name: "dlclose",
        return_type: "int",
        param_count: 1,
        param_types: &["void*"],
        is_noreturn: false,
        is_pure: false,
    },
];
