fn main() {
    tauri_build::build();
    if cfg!(feature = "tsexport") {
        let dir_contents = std::fs::read_dir("../../bindings").unwrap();
        let mut result = String::new();
        result.push_str("// Generated by cargo ts\n");
        for entry in dir_contents {
            let entry = entry.unwrap();
            let path = entry.path();
            let content = std::fs::read_to_string(&path).unwrap();
            for line in content.lines() {
                if line.starts_with("//") || line.starts_with("import") {
                    continue;
                }
                result.push_str(&line);
                result.push_str("\n");
            }
        }
        std::fs::write("../../firebat/src/bindings.ts", result).unwrap();
    }
}
