[package]
name = "fireman"
version = "0.0.1"
edition = "2021"
authors = ["Eveheeero <xhve00000@gmail.com>"]
repository = "https://github.com/Eveheeero/fireman"
license = "GPL-2.0"
description = "Running Binary of Fireball"
homepage = "https://crates.io/crates/fireman"

[dependencies]
fireball = { path = "../fireball", version = "0.0.1" }
clap = { version = "4.5.37", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
