# https://docs.github.com/en/actions/using-workflows/about-workflows
name: Rust

on:
    push:
        branches: ["**"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        strategy:
            matrix:
                os:
                    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
                    [
                        # windows-latest,
                        windows-2022,
                        windows-2019,
                        # ubuntu-latest,
                        ubuntu-22.04,
                        ubuntu-20.04,
                        # macos-latest,
                        macos-12,
                        macos-11,
                    ]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3
            - name: Build Debug
              run: cargo build --verbose
            - name: Build Release
              run: cargo build --release --verbose

    test:
        needs: build
        strategy:
            matrix:
                os:
                    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
                    [
                        # windows-latest,
                        windows-2022,
                        windows-2019,
                        # ubuntu-latest,
                        ubuntu-22.04,
                        ubuntu-20.04,
                        # macos-latest,
                        macos-12,
                        macos-11,
                    ]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3
            - name: Test Debug
              run: cargo test --verbose
            - name: Test Release
              run: cargo test --release --verbose
