[package]
name = "fireball"
version = "0.0.1"
edition = "2021"
authors = ["Eveheeero <xhve00000@gmail.com>"]
repository = "https://github.com/Eveheeero/fireman"
license = "MIT"
description = "Decompiler library inspired by snowman"
homepage = "https://crates.io/crates/fireball"

[lib]
crate-type = ["cdylib", "rlib", "staticlib"]

[dependencies]
goblin = "0.6.1"
cpp_demangle = "0.4.0"
capstone = "0.11.0"
pdb = "0.8.0"
once_cell = "1.17.1"
regex = "1.7.0"
log = { version = "0.4.17", features = ["std", "serde", "max_level_trace", "release_max_level_off"]}
simplelog = "0.12.0"
bitvec = "1.0.1"
