[package]
name = "fireball"
version = "0.0.1"
edition = "2021"
authors = ["Eveheeero <xhve00000@gmail.com>"]
repository = "https://github.com/Eveheeero/fireman"
license = "MIT"
description = "Decompiler library inspired by snowman"
homepage = "https://crates.io/crates/fireball"

[lib]
crate-type = ["cdylib", "rlib", "staticlib"]

[dependencies]
goblin = "0.5.4"
cpp_demangle = "0.3.5"
capstone = "0.11.0"
pdb = "0.8.0"
lazy_static = "1.4.0"
regex = "1.7.0"
